Merge changes from 1.11.x.
CVS-ID: doc/ChangeLog 1.748
CVS-ID: doc/stamp-vti 1.35
CVS-ID: doc/version.texi 1.36
CVS-ID: src/ChangeLog 1.2404
CVS-ID: src/client.c 1.325
CVS-ID: src/client.h 1.40
CVS-ID: ChangeLog 1.710
CVS-ID: configure 1.183
CVS-ID: configure.in 1.185

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9539,8 +9539,8 @@ echo "${ECHO_T}$EDITOR" >&6
   if ! test -f $with_editor \
       || ! test -x $with_editor; then
     # warn the user that they may encounter problems
-    { echo "$as_me:$LINENO: WARNING: $with_editor is not a path to an executable file" >&5
-echo "$as_me: WARNING: $with_editor is not a path to an executable file" >&2;}
+    { echo "$as_me:$LINENO: WARNING: \`$with_editor' is not a path to an executable file" >&5
+echo "$as_me: WARNING: \`$with_editor' is not a path to an executable file" >&2;}
   fi
 elif test no != "${with_editor}"; then
   # Search for an editor
@@ -9585,10 +9585,9 @@ fi
 done
 
 else
-  echo "$as_me:$LINENO: checking for an editor" >&5
-echo $ECHO_N "checking for an editor... $ECHO_C" >&6
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
+  { { echo "$as_me:$LINENO: error: CVS cannot be compiled without a default log message editor.  Try \`configure --with-editor'." >&5
+echo "$as_me: error: CVS cannot be compiled without a default log message editor.  Try \`configure --with-editor'." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 if test -n "${EDITOR}"; then
