* aclocal.m4, gnulib.txt: Update from GNULIB. * lib/mktime.c, lib/regex.c, lib/stdint_.h, lib/strftime.c, lib/strtol.c: Ditto. * m4/chdir-long.m4, m4/closeout.m4, m4/dirname.m4, m4/exitfail.m4, m4/fpending.m4, m4/getcwd.m4, m4/getdate.m4, m4/getline.m4, m4/getpagesize.m4, m4/getpass.m4, m4/gettext.m4, m4/gnulib.m4, m4/lib-link.m4, m4/md5.m4, m4/memrchr.m4, m4/nanosleep.m4, m4/nls.m4, m4/pathmax.m4, m4/po.m4, m4/quotearg.m4, m4/stat-macros.m4, m4/stdint.m4, m4/strftime.m4, m4/timespec.m4, m4/unlocked-io.m4, m4/xalloc.m4, m4/yesno.m4: Ditto. * windows-NT/Makefile.am, windows-NT/stdint.h: Ditto.
* Makefile.in, config.h.in, configure: Regenerated.
* src/Makefile.in: Regenerated.
* contrib/Makefile.in: Ditto.
* contrib/pam/Makefile.in: Ditto.
* diff/Makefile.in: Ditto.
* doc/Makefile.in: Ditto.
* doc/i18n/Makefile.in: Ditto.
* doc/i18n/pt_BR/Makefile.in: Ditto.
* man/Makefile.in: Ditto.
* src/Makefile.in: Ditto.
* tools/Makefile.in: Ditto.
* vms/Makefile.in: Ditto.
* windows-NT/Makefile.in: Ditto.
* windows-NT/SCC/Makefile.in: Ditto.

CVS-ID: contrib/pam/ChangeLog 1.5
CVS-ID: contrib/pam/Makefile.in 1.23
CVS-ID: contrib/ChangeLog 1.149
CVS-ID: contrib/Makefile.in 1.100
CVS-ID: diff/ChangeLog 1.112
CVS-ID: diff/Makefile.in 1.71
CVS-ID: doc/i18n/pt_BR/ChangeLog 1.12
CVS-ID: doc/i18n/pt_BR/Makefile.in 1.6
CVS-ID: doc/i18n/ChangeLog 1.3
CVS-ID: doc/i18n/Makefile.in 1.6
CVS-ID: doc/ChangeLog 1.895
CVS-ID: doc/Makefile.in 1.108
CVS-ID: lib/ChangeLog 1.407
CVS-ID: lib/Makefile.am 1.93
CVS-ID: lib/Makefile.gnulib 1.47
CVS-ID: lib/Makefile.in 1.173
CVS-ID: lib/mktime.c 1.8
CVS-ID: lib/regex.c 1.17
CVS-ID: lib/stdint_.h 1.2
CVS-ID: lib/strftime.c 1.5
CVS-ID: lib/strtol.c 1.3
CVS-ID: m4/ChangeLog 1.113
CVS-ID: m4/chdir-long.m4 1.2
CVS-ID: m4/closeout.m4 1.2
CVS-ID: m4/dirname.m4 1.4
CVS-ID: m4/exitfail.m4 1.3
CVS-ID: m4/fpending.m4 1.2
CVS-ID: m4/getcwd.m4 1.3
CVS-ID: m4/getdate.m4 1.3
CVS-ID: m4/getline.m4 1.10
CVS-ID: m4/getpagesize.m4 1.4
CVS-ID: m4/getpass.m4 1.6
CVS-ID: m4/gettext.m4 1.7
CVS-ID: m4/gnulib.m4 1.43
CVS-ID: m4/lib-link.m4 1.4
CVS-ID: m4/md5.m4 1.3
CVS-ID: m4/memrchr.m4 1.2
CVS-ID: m4/nanosleep.m4 1.3
CVS-ID: m4/nls.m4 1.3
CVS-ID: m4/pathmax.m4 1.3
CVS-ID: m4/po.m4 1.4
CVS-ID: m4/quotearg.m4 1.2
CVS-ID: m4/stat-macros.m4 1.1
CVS-ID: m4/stdint.m4 1.3
CVS-ID: m4/strftime.m4 1.4
CVS-ID: m4/timespec.m4 1.3
CVS-ID: m4/unlocked-io.m4 1.6
CVS-ID: m4/xalloc.m4 1.4
CVS-ID: m4/yesno.m4 1.5
CVS-ID: man/ChangeLog 1.78
CVS-ID: man/Makefile.in 1.73
CVS-ID: src/ChangeLog 1.3168
CVS-ID: src/Makefile.in 1.143
CVS-ID: tools/ChangeLog 1.37
CVS-ID: tools/Makefile.in 1.63
CVS-ID: vms/ChangeLog 1.100
CVS-ID: vms/Makefile.in 1.64
CVS-ID: windows-NT/SCC/ChangeLog 1.53
CVS-ID: windows-NT/SCC/Makefile.in 1.57
CVS-ID: windows-NT/ChangeLog 1.296
CVS-ID: windows-NT/Makefile.am 1.27
CVS-ID: windows-NT/Makefile.in 1.90
CVS-ID: windows-NT/stdint.h 1.2
CVS-ID: ChangeLog 1.1183
CVS-ID: Makefile.in 1.159
CVS-ID: aclocal.m4 1.132
CVS-ID: config.h.in 1.164
CVS-ID: configure 1.377
CVS-ID: gnulib.txt 1.44

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -327,7 +327,7 @@ ac_includes_default="\
 
 gl_func_list=
 gl_header_list=
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar ac_prefix_program MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP RANLIB ac_ct_RANLIB LN_S PERL CSH MKTEMP SENDMAIL PR ROFF PS2PDF TEXI2DVI MAKE_TARGETS_IN_VPATH_TRUE MAKE_TARGETS_IN_VPATH_FALSE LIBOBJS ALLOCA ALLOCA_H STDBOOL_H HAVE__BOOL FNMATCH_H YACC YFLAGS LIB_CLOCK_GETTIME GETOPT_H LIB_NANOSLEEP HAVE_LONG_64BIT HAVE_LONGLONG_64BIT STDINT_H EOVERFLOW MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE build build_cpu build_vendor build_os host host_cpu host_vendor host_os INTL_MACOSX_LIBS LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB HAVE_PUTENV cvs_client_objects KRB4 ZLIB_SUBDIRS ZLIB_CPPFLAGS ZLIB_LIBS with_default_rsh RSH_DFLT EDITOR LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar ac_prefix_program MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP RANLIB ac_ct_RANLIB LN_S PERL CSH MKTEMP SENDMAIL PR ROFF PS2PDF TEXI2DVI MAKE_TARGETS_IN_VPATH_TRUE MAKE_TARGETS_IN_VPATH_FALSE LIBOBJS ALLOCA ALLOCA_H STDBOOL_H HAVE__BOOL FNMATCH_H YACC YFLAGS LIB_CLOCK_GETTIME GETOPT_H LIB_NANOSLEEP HAVE_LONG_64BIT HAVE_LONG_LONG_64BIT STDINT_H EOVERFLOW MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE build build_cpu build_vendor build_os host host_cpu host_vendor host_os INTL_MACOSX_LIBS LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB HAVE_PUTENV cvs_client_objects KRB4 ZLIB_SUBDIRS ZLIB_CPPFLAGS ZLIB_LIBS with_default_rsh RSH_DFLT EDITOR LTLIBOBJS'
 ac_subst_files='MKTEMP_SH_FUNCTION'
 
 # Initialize some variables set by options.
@@ -9054,6 +9054,80 @@ esac
 
 
 
+      echo "$as_me:$LINENO: checking whether memrchr is declared" >&5
+echo $ECHO_N "checking whether memrchr is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_memrchr+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef memrchr
+  char *p = (char *) memrchr;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_memrchr=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_memrchr=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_memrchr" >&5
+echo "${ECHO_T}$ac_cv_have_decl_memrchr" >&6
+if test $ac_cv_have_decl_memrchr = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_MEMRCHR 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_MEMRCHR 0
+_ACEOF
+
+
+fi
+
+
+
+
     echo "$as_me:$LINENO: checking whether system is Windows or MSDOS" >&5
 echo $ECHO_N "checking whether system is Windows or MSDOS... $ECHO_C" >&6
 if test "${ac_cv_win_or_dos+set}" = set; then
@@ -9498,6 +9572,8 @@ _ACEOF
    fi
 
 
+
+
   :
 
 
@@ -9783,6 +9859,8 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+
 
 
 
@@ -13176,6 +13254,16 @@ _ACEOF
 
 
 
+
+ case $LIBOBJS in
+    "strftime.$ac_objext"   | \
+  *" strftime.$ac_objext"   | \
+    "strftime.$ac_objext "* | \
+  *" strftime.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS strftime.$ac_objext" ;;
+esac
+
+
  # strftime.c uses the underyling system strftime if it exists.
 
 
@@ -16514,10 +16602,159 @@ _ACEOF
   esac
 
 
+
+
+
+
+
+  :
+
+
+
+
+
+
+
+for ac_func in memrchr
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  case $LIBOBJS in
+    "$ac_func.$ac_objext"   | \
+  *" $ac_func.$ac_objext"   | \
+    "$ac_func.$ac_objext "* | \
+  *" $ac_func.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS $ac_func.$ac_objext" ;;
+esac
+
+fi
+done
+
+
+  if test $ac_cv_func_memrchr = no; then
+    :
   fi
 
 
+  fi
+
+
+
+  case $LIBOBJS in
+    "closeout.$ac_objext"   | \
+  *" closeout.$ac_objext"   | \
+    "closeout.$ac_objext "* | \
+  *" closeout.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS closeout.$ac_objext" ;;
+esac
+
+
     :
+
+
+
+  case $LIBOBJS in
+    "dirname.$ac_objext"   | \
+  *" dirname.$ac_objext"   | \
+    "dirname.$ac_objext "* | \
+  *" dirname.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS dirname.$ac_objext" ;;
+esac
 
 
 
@@ -16656,6 +16893,16 @@ done
 
   :
 
+
+
+
+  case $LIBOBJS in
+    "exitfail.$ac_objext"   | \
+  *" exitfail.$ac_objext"   | \
+    "exitfail.$ac_objext "* | \
+  *" exitfail.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS exitfail.$ac_objext" ;;
+esac
 
 
     :
@@ -17076,6 +17323,8 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
   fi
+
+
 
 
 
@@ -18001,6 +18250,16 @@ _ACEOF
 
 
 
+  case $LIBOBJS in
+    "getdate.$ac_objext"   | \
+  *" getdate.$ac_objext"   | \
+    "getdate.$ac_objext "* | \
+  *" getdate.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS getdate.$ac_objext" ;;
+esac
+
+
+
 
 
 
@@ -18424,6 +18683,8 @@ done
 
 
   fi
+
+
 
 
 
@@ -19101,6 +19362,8 @@ _ACEOF
 
 
 
+
+
   :
 
 
@@ -19361,6 +19624,8 @@ _ACEOF
 
 fi
 done
+
+
 
 
 
@@ -19857,6 +20122,16 @@ fi
 
 
 
+  case $LIBOBJS in
+    "md5.$ac_objext"   | \
+  *" md5.$ac_objext"   | \
+    "md5.$ac_objext "* | \
+  *" md5.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS md5.$ac_objext" ;;
+esac
+
+
+
 
 
   :
@@ -20102,6 +20377,14 @@ done
   :
 
   fi
+
+
+
+
+
+
+
+  :
 
 
 
@@ -20793,6 +21076,8 @@ _ACEOF
   fi
 
 
+
+
  nanosleep_save_libs=$LIBS
 
  # Solaris 2.5.1 needs -lposix4 to get the nanosleep function.
@@ -21188,6 +21473,8 @@ esac
 
 
 
+
+
   :
 
 
@@ -21197,6 +21484,16 @@ esac
 
 
 
+
+
+
+  case $LIBOBJS in
+    "quotearg.$ac_objext"   | \
+  *" quotearg.$ac_objext"   | \
+    "quotearg.$ac_objext "* | \
+  *" quotearg.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS quotearg.$ac_objext" ;;
+esac
 
 
 
@@ -23046,6 +23343,9 @@ fi
 
 
 
+
+
+
   # Define two additional variables used in the Makefile substitution.
 
   if test "$ac_cv_header_stdbool_h" = yes; then
@@ -23403,9 +23703,9 @@ fi
 echo "$as_me:$LINENO: result: $gl_cv_longlong_bitsize_64" >&5
 echo "${ECHO_T}$gl_cv_longlong_bitsize_64" >&6
   if test $gl_cv_longlong_bitsize_64 = yes; then
-    HAVE_LONGLONG_64BIT=1
+    HAVE_LONG_LONG_64BIT=1
   else
-    HAVE_LONGLONG_64BIT=0
+    HAVE_LONG_LONG_64BIT=0
   fi
 
 
@@ -24226,6 +24526,8 @@ esac
 
 
 
+
+
   :
 
 
@@ -24582,6 +24884,8 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
   fi
+
+
 
 
 
@@ -25099,6 +25403,16 @@ esac
 
 
 
+  case $LIBOBJS in
+    "xmalloc.$ac_objext"   | \
+  *" xmalloc.$ac_objext"   | \
+    "xmalloc.$ac_objext "* | \
+  *" xmalloc.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS xmalloc.$ac_objext" ;;
+esac
+
+
+
   :
 
 
@@ -25274,7 +25588,18 @@ done
 
 
 
+
+  case $LIBOBJS in
+    "yesno.$ac_objext"   | \
+  *" yesno.$ac_objext"   | \
+    "yesno.$ac_objext "* | \
+  *" yesno.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS yesno.$ac_objext" ;;
+esac
+
+
     :
+
 
 
 
@@ -25770,6 +26095,7 @@ fi
 echo "$as_me:$LINENO: result: $acl_cv_prog_gnu_ld" >&5
 echo "${ECHO_T}$acl_cv_prog_gnu_ld" >&6
 with_gnu_ld=$acl_cv_prog_gnu_ld
+
 
 
 
@@ -39487,7 +39813,7 @@ s,@LIB_CLOCK_GETTIME@,$LIB_CLOCK_GETTIME,;t t
 s,@GETOPT_H@,$GETOPT_H,;t t
 s,@LIB_NANOSLEEP@,$LIB_NANOSLEEP,;t t
 s,@HAVE_LONG_64BIT@,$HAVE_LONG_64BIT,;t t
-s,@HAVE_LONGLONG_64BIT@,$HAVE_LONGLONG_64BIT,;t t
+s,@HAVE_LONG_LONG_64BIT@,$HAVE_LONG_LONG_64BIT,;t t
 s,@STDINT_H@,$STDINT_H,;t t
 s,@EOVERFLOW@,$EOVERFLOW,;t t
 s,@MKINSTALLDIRS@,$MKINSTALLDIRS,;t t
@@ -40242,6 +40568,9 @@ done
           /*) top_srcdir="$ac_given_srcdir" ;;
           *)  top_srcdir="$ac_dots$ac_given_srcdir" ;;
         esac
+        # Treat a directory as a PO directory if and only if it has a
+        # POTFILES.in file. This allows packages to have multiple PO
+        # directories under different names or in different locations.
         if test -f "$ac_given_srcdir/$ac_dir/POTFILES.in"; then
           rm -f "$ac_dir/POTFILES"
           test -n "$as_me" && echo "$as_me: creating $ac_dir/POTFILES" || echo "creating $ac_dir/POTFILES"
@@ -40255,7 +40584,7 @@ done
             if test -n "$OBSOLETE_ALL_LINGUAS"; then
               test -n "$as_me" && echo "$as_me: setting ALL_LINGUAS in configure.in is obsolete" || echo "setting ALL_LINGUAS in configure.in is obsolete"
             fi
-            ALL_LINGUAS_=`sed -e "/^#/d" "$ac_given_srcdir/$ac_dir/LINGUAS"`
+            ALL_LINGUAS_=`sed -e "/^#/d" -e "s/#.*//" "$ac_given_srcdir/$ac_dir/LINGUAS"`
             # Hide the ALL_LINGUAS assigment from automake.
             eval 'ALL_LINGUAS''=$ALL_LINGUAS_'
             POMAKEFILEDEPS="$POMAKEFILEDEPS LINGUAS"
