Regenerated.
CVS-ID: contrib/pam/Makefile.in 1.67
CVS-ID: contrib/Makefile.in 1.146
CVS-ID: diff/Makefile.in 1.115
CVS-ID: maint-aux/Makefile.in 1.48
CVS-ID: maint-aux/gnulib-filelist.txt 1.35
CVS-ID: man/Makefile.in 1.117
CVS-ID: tools/Makefile.in 1.107
CVS-ID: vms/Makefile.in 1.111
CVS-ID: Makefile.in 1.207
CVS-ID: aclocal.m4 1.168
CVS-ID: config.h.in 1.228
CVS-ID: configure 1.485

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2118,10 +2118,11 @@ ac_func_list="$ac_func_list getpwnam_r"
 ac_header_list="$ac_header_list stdint.h"
 ac_header_list="$ac_header_list wchar.h"
 ac_header_list="$ac_header_list inttypes.h"
+ac_func_list="$ac_func_list lchmod"
+ac_func_list="$ac_func_list fchmod"
 ac_func_list="$ac_func_list alarm"
 ac_func_list="$ac_func_list siginterrupt"
 ac_header_list="$ac_header_list sys/select.h"
-ac_func_list="$ac_func_list lchmod"
 ac_func_list="$ac_func_list fdopendir"
 ac_func_list="$ac_func_list mbsinit"
 ac_header_list="$ac_header_list locale.h"
@@ -13939,6 +13940,8 @@ fi
 
 
 
+
+
   { echo "$as_me:$LINENO: checking for nl_langinfo and CODESET" >&5
 echo $ECHO_N "checking for nl_langinfo and CODESET... $ECHO_C" >&6; }
 if test "${am_cv_langinfo_codeset+set}" = set; then
@@ -14634,6 +14637,8 @@ _ACEOF
 
 
 
+
+
   GNULIB_GETSUBOPT=0;
   GNULIB_MKDTEMP=0;
   GNULIB_MKSTEMP=0;
@@ -14648,8 +14653,6 @@ _ACEOF
   REPLACE_NANOSLEEP=GNULIB_PORTCHECK;
   REPLACE_STRPTIME=GNULIB_PORTCHECK;
   REPLACE_TIMEGM=GNULIB_PORTCHECK;
-
-
 
 
 
@@ -23746,6 +23749,14 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
 
+
+
+
+
+
+
+
+
 for ac_func in lchown
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -24901,6 +24912,9 @@ done
 
 
 
+  gl_LIBOBJS="$gl_LIBOBJS mkancesdirs.$ac_objext"
+
+
 
 
 
@@ -24986,6 +25000,19 @@ _ACEOF
 
     :
   fi
+
+
+  gl_LIBOBJS="$gl_LIBOBJS dirchownmod.$ac_objext"
+  gl_LIBOBJS="$gl_LIBOBJS mkdir-p.$ac_objext"
+
+
+
+
+
+
+
+
+
 
 
 
@@ -26201,6 +26228,10 @@ _ACEOF
 
 
 
+  gl_LIBOBJS="$gl_LIBOBJS quote.$ac_objext"
+
+
+
   gl_LIBOBJS="$gl_LIBOBJS quotearg.$ac_objext"
 
 
@@ -26336,6 +26367,102 @@ _ACEOF
 
   fi
 
+
+
+for ac_func in raise
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6; }
+if { as_var=$as_ac_var; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_$ac_func || defined __stub___$ac_func
+choke me
+#endif
+
+int
+main ()
+{
+return $ac_func ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	eval "$as_ac_var=no"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+ac_res=`eval echo '${'$as_ac_var'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  gl_LIBOBJS="$gl_LIBOBJS $ac_func.$ac_objext"
+fi
+done
 
 
 
@@ -27161,6 +27288,7 @@ done
 
 
   gl_LIBOBJS="$gl_LIBOBJS save-cwd.$ac_objext"
+
 
 
 
