* configure.in: Call gl_TIME_R. * srclist.txt (time_r): New module. * Makefile.in, aclocal.m4, config.h.in, configure: Regenerated.
CVS-ID: ChangeLog 1.994
CVS-ID: Makefile.in 1.122
CVS-ID: aclocal.m4 1.82
CVS-ID: config.h.in 1.126
CVS-ID: configure 1.292
CVS-ID: configure.in 1.283
CVS-ID: srclist.txt 1.34

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14208,6 +14208,86 @@ done
 
 
 
+
+  echo "$as_me:$LINENO: checking whether localtime_r is compatible with its POSIX signature" >&5
+echo $ECHO_N "checking whether localtime_r is compatible with its POSIX signature... $ECHO_C" >&6
+if test "${gl_cv_time_r_posix+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <time.h>
+int
+main ()
+{
+/* We don't need to append 'restrict's to the argument types,
+	   even though the POSIX signature has the 'restrict's,
+	   since C99 says they can't affect type compatibility.  */
+	struct tm * (*ptr) (time_t const *, struct tm *) = localtime_r;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gl_cv_time_r_posix=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gl_cv_time_r_posix=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $gl_cv_time_r_posix" >&5
+echo "${ECHO_T}$gl_cv_time_r_posix" >&6
+  if test $gl_cv_time_r_posix = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TIME_R_POSIX 1
+_ACEOF
+
+  else
+    case $LIBOBJS in
+    "time_r.$ac_objext"   | \
+  *" time_r.$ac_objext"   | \
+    "time_r.$ac_objext "* | \
+  *" time_r.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS time_r.$ac_objext" ;;
+esac
+
+
+  :
+
+  fi
+
+
+
+
   :
 
 
