Merge changes from 1.11.x.
CVS-ID: contrib/pam/Makefile.in 1.69
CVS-ID: contrib/Makefile.in 1.148
CVS-ID: diff/Makefile.in 1.117
CVS-ID: doc/i18n/pt_BR/Makefile.in 1.53
CVS-ID: doc/i18n/Makefile.in 1.52
CVS-ID: doc/ChangeLog 1.985
CVS-ID: doc/Makefile.in 1.164
CVS-ID: doc/cvs.texinfo 1.705
CVS-ID: doc/stamp-vti 1.208
CVS-ID: doc/version.texi 1.210
CVS-ID: lib/Makefile.in 1.233
CVS-ID: maint-aux/Makefile.in 1.50
CVS-ID: man/Makefile.in 1.119
CVS-ID: src/ChangeLog 1.3557
CVS-ID: src/Makefile.in 1.191
CVS-ID: src/client.h 1.66
CVS-ID: src/log.c 1.113
CVS-ID: src/main.c 1.277
CVS-ID: src/recurse.c 1.130
CVS-ID: src/root.c 1.132
CVS-ID: src/rsh-client.c 1.15
CVS-ID: tools/Makefile.in 1.109
CVS-ID: vms/Makefile.in 1.113
CVS-ID: windows-NT/SCC/Makefile.in 1.103
CVS-ID: windows-NT/ChangeLog 1.396
CVS-ID: windows-NT/Makefile.in 1.143
CVS-ID: windows-NT/config.h 1.219
CVS-ID: windows-NT/config.h.in 1.147
CVS-ID: ChangeLog 1.1364
CVS-ID: Makefile.in 1.209
CVS-ID: NEWS 1.377
CVS-ID: config.h.in 1.231
CVS-ID: configure 1.488
CVS-ID: configure.in 1.385

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -953,6 +953,8 @@ KRB4
 ZLIB_SUBDIRS
 ZLIB_CPPFLAGS
 ZLIB_LIBS
+with_default_ssh
+SSH_DFLT
 with_default_rsh
 RSH_DFLT
 EDITOR
@@ -1658,6 +1660,8 @@ Optional Packages:
   --with-gssapi           GSSAPI directory (default autoselects)
   --with-external-zlib    Use the specified ZLIB library (defaults to the
                           version distributed with the CVS source)
+  --with-ssh              The default remote shell CVS will use for :extssh:
+                          transport (default ssh)
   --with-rsh              The default remote shell CVS will use for :ext:
                           transport (default ssh)
   --with-editor           The default text editor CVS should use for log
@@ -43528,6 +43532,94 @@ fi
 
 # What remote shell transport should our client cvs default to using?
 
+# Check whether --with-ssh was given.
+if test "${with_ssh+set}" = set; then
+  withval=$with_ssh;
+else
+  with_ssh="ssh lshc ssh2"
+fi
+
+
+if test no = "$with_ssh"; then
+  { echo "$as_me:$LINENO: WARNING: Failed to find usable remote shell. Using 'ssh'." >&5
+echo "$as_me: WARNING: Failed to find usable remote shell. Using 'ssh'." >&2;}
+  with_ssh=ssh
+elif test yes = "$with_ssh"; then
+  # Make --with-ssh mean the same thing as --with-ssh=ssh
+  with_ssh=ssh
+fi
+
+if echo $with_ssh |grep ^/ >/dev/null; then
+  # If $with_ssh is an absolute path, issue a warning if the executable
+  # doesn't exist or isn't usable, but then trust the user and use it
+  # regardless
+  with_default_ssh=$with_ssh
+  { echo "$as_me:$LINENO: checking for a remote shell" >&5
+echo $ECHO_N "checking for a remote shell... $ECHO_C" >&6; }
+  if ! test -f $with_ssh \
+      || ! test -x $with_ssh; then
+    # warn the user that they may encounter problems
+    { echo "$as_me:$LINENO: WARNING: $with_ssh is not a path to an executable file" >&5
+echo "$as_me: WARNING: $with_ssh is not a path to an executable file" >&2;}
+  fi
+else
+  # Search for a remote shell
+  for ac_prog in $with_ssh
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_with_default_ssh+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$with_default_ssh"; then
+  ac_cv_prog_with_default_ssh="$with_default_ssh" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_with_default_ssh="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+with_default_ssh=$ac_cv_prog_with_default_ssh
+if test -n "$with_default_ssh"; then
+  { echo "$as_me:$LINENO: result: $with_default_ssh" >&5
+echo "${ECHO_T}$with_default_ssh" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$with_default_ssh" && break
+done
+test -n "$with_default_ssh" || with_default_ssh=""ssh""
+
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define SSH_DFLT "$with_default_ssh"
+_ACEOF
+
+SSH_DFLT=$with_default_ssh
+
+
+
+# What remote shell transport should our client cvs default to using?
+
 # Check whether --with-rsh was given.
 if test "${with_rsh+set}" = set; then
   withval=$with_rsh;
@@ -46449,6 +46541,8 @@ KRB4!$KRB4$ac_delim
 ZLIB_SUBDIRS!$ZLIB_SUBDIRS$ac_delim
 ZLIB_CPPFLAGS!$ZLIB_CPPFLAGS$ac_delim
 ZLIB_LIBS!$ZLIB_LIBS$ac_delim
+with_default_ssh!$with_default_ssh$ac_delim
+SSH_DFLT!$SSH_DFLT$ac_delim
 with_default_rsh!$with_default_rsh$ac_delim
 RSH_DFLT!$RSH_DFLT$ac_delim
 EDITOR!$EDITOR$ac_delim
@@ -46458,7 +46552,7 @@ gl_LIBOBJS!$gl_LIBOBJS$ac_delim
 gl_LTLIBOBJS!$gl_LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 43; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
