Regenerated.
CVS-ID: configure 1.388

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19418,7 +19418,13 @@ fi
     fi
 
             if test -z "$GETOPT_H"; then
-      echo "$as_me:$LINENO: checking whether getopt_clip is declared" >&5
+      echo "$as_me:$LINENO: checking for working GNU getopt function" >&5
+echo $ECHO_N "checking for working GNU getopt function... $ECHO_C" >&6
+if test "${gl_cv_func_gnu_getopt+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+                             echo "$as_me:$LINENO: checking whether getopt_clip is declared" >&5
 echo $ECHO_N "checking whether getopt_clip is declared... $ECHO_C" >&6
 if test "${ac_cv_have_decl_getopt_clip+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19476,9 +19482,61 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_have_decl_getopt_clip" >&5
 echo "${ECHO_T}$ac_cv_have_decl_getopt_clip" >&6
 if test $ac_cv_have_decl_getopt_clip = yes; then
-  GETOPT_H=getopt.h
+  gl_cv_func_gnu_getopt=no
+else
+  gl_cv_func_gnu_getopt=yes
 fi
 
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <getopt.h>
+int
+main ()
+{
+
+	     char *myargv[3];
+	     myargv[0] = "conftest";
+	     myargv[1] = "-+";
+	     myargv[2] = 0;
+	     return getopt (2, myargv, "+a") != '?';
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gl_cv_func_gnu_getopt=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+gl_cv_func_gnu_getopt=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $gl_cv_func_gnu_getopt" >&5
+echo "${ECHO_T}$gl_cv_func_gnu_getopt" >&6
+      if test "$gl_cv_func_gnu_getopt" = "no"; then
+	GETOPT_H=getopt.h
+      fi
     fi
 
     if test -n "$GETOPT_H"; then
