* aclocal.m4 (AM_MAINTAINER_MODE): New macro to support --enable-maintainer-mode. * configure.in: Use it. * configure: Regenerated. * Makefile.in: Regenerated. * noautomake.sh: Removed; no longer needed. * INSTALL: Remove reference to noautomake.sh, add reference to --enable-maintainer-mode. * Makefile.am: Remove noautomake.sh. * NEWS: Add note about --enable-maintainer-mode and noautomake.sh. * README: Remove noautomake.sh.
CVS-ID: contrib/ChangeLog 1.100
CVS-ID: contrib/Makefile.in 1.57
CVS-ID: diff/ChangeLog 1.66
CVS-ID: diff/Makefile.in 1.32
CVS-ID: doc/ChangeLog 1.750
CVS-ID: doc/Makefile.in 1.60
CVS-ID: lib/ChangeLog 1.175
CVS-ID: lib/Makefile.in 1.67
CVS-ID: man/ChangeLog 1.66
CVS-ID: man/Makefile.in 1.37
CVS-ID: src/ChangeLog 1.2417
CVS-ID: src/Makefile.in 1.89
CVS-ID: tools/ChangeLog 1.26
CVS-ID: tools/Makefile.in 1.28
CVS-ID: vms/ChangeLog 1.81
CVS-ID: vms/Makefile.in 1.27
CVS-ID: windows-NT/SCC/ChangeLog 1.45
CVS-ID: windows-NT/SCC/Makefile.in 1.23
CVS-ID: windows-NT/ChangeLog 1.163
CVS-ID: windows-NT/Makefile.in 1.34
CVS-ID: ChangeLog 1.717
CVS-ID: INSTALL 1.145
CVS-ID: Makefile.am 1.11
CVS-ID: Makefile.in 1.93
CVS-ID: NEWS 1.124
CVS-ID: README 1.39
CVS-ID: aclocal.m4 1.25
CVS-ID: configure 1.186
CVS-ID: configure.in 1.188
CVS-ID: noautomake.sh 1.4 (deleted)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -849,6 +849,8 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-maintainer-mode enable make rules and dependencies not useful
+                          (and sometimes confusing) to the casual installer
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-cvs-ndbm       Use the NDBM library distributed with CVS rather
@@ -1735,6 +1737,30 @@ fi
 # along with our hook.
 ac_config_headers="$ac_config_headers config.h"
 
+
+
+echo "$as_me:$LINENO: checking whether to enable maintainer-specific portions of Makefiles" >&5
+echo $ECHO_N "checking whether to enable maintainer-specific portions of Makefiles... $ECHO_C" >&6
+    # Check whether --enable-maintainer-mode or --disable-maintainer-mode was given.
+if test "${enable_maintainer_mode+set}" = set; then
+  enableval="$enable_maintainer_mode"
+  USE_MAINTAINER_MODE=$enableval
+else
+  USE_MAINTAINER_MODE=no
+fi;
+  echo "$as_me:$LINENO: result: $USE_MAINTAINER_MODE" >&5
+echo "${ECHO_T}$USE_MAINTAINER_MODE" >&6
+
+
+if test $USE_MAINTAINER_MODE = yes; then
+  MAINTAINER_MODE_TRUE=
+  MAINTAINER_MODE_FALSE='#'
+else
+  MAINTAINER_MODE_TRUE='#'
+  MAINTAINER_MODE_FALSE=
+fi
+
+  MAINT=$MAINTAINER_MODE_TRUE
 
 
 
@@ -10211,6 +10237,13 @@ fi
 
 DEFS=-DHAVE_CONFIG_H
 
+if test -z "${MAINTAINER_MODE_TRUE}" && test -z "${MAINTAINER_MODE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -10766,6 +10799,9 @@ s,@INSTALL_STRIP_PROGRAM@,$INSTALL_STRIP_PROGRAM,;t t
 s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@ac_prefix_program@,$ac_prefix_program,;t t
+s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
+s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
+s,@MAINT@,$MAINT,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
