* configure.in (WITH_RSH): Add --with-rsh configure option. The default is still "rsh" but it will look for "ssh" if "rsh" is not found on the system.
* doc/cvs.texinfo (Connecting via rsh): Document that --with-rsh may
be used to specify the default "rsh" program to use.

* man/cvs.1 (CVS_RSH): Note that the default "rsh" value may be set by
the --with-rsh configure option.

* src/client.c (start_rsh_server): Use new definition of RSH_DFLT to
allow "rsh" to be configured to default to "ssh" or some other
local remote transport program.

* emx/config.h (RSH_DFLT): Default to "rsh".
* os2/config.h (RSH_DFLT): Ditto.
* vms/config.h (RSH_DFLT): Ditto.
* windows-NT/config.h (RSH_DFLT): Ditto.

* configure: Regenerated.
* config.h.in: Ditto.
* Makefile.in: Ditto.
* contrib/Makefile.in: Ditto.
* diff/Makefile.in: Ditto.
* doc/Makefile.in: Ditto.
* lib/Makefile.in: Ditto.
* man/Makefile.in: Ditto.
* src/Makefile.in: Ditto.
* tools/Makefile.in: Ditto.
* vms/Makefile.in: Ditto.
* windows-NT/Makefile.in: Ditto.
* windows-NT/SCC/Makefile.in: Ditto.

CVS-ID: contrib/ChangeLog 1.95
CVS-ID: contrib/Makefile.in 1.55
CVS-ID: diff/ChangeLog 1.65
CVS-ID: diff/Makefile.in 1.31
CVS-ID: doc/ChangeLog 1.743
CVS-ID: doc/Makefile.in 1.58
CVS-ID: doc/cvs.texinfo 1.562
CVS-ID: emx/ChangeLog 1.35
CVS-ID: emx/config.h 1.9
CVS-ID: lib/ChangeLog 1.172
CVS-ID: lib/Makefile.in 1.64
CVS-ID: man/ChangeLog 1.64
CVS-ID: man/Makefile.in 1.35
CVS-ID: man/cvs.1 1.35
CVS-ID: os2/ChangeLog 1.193
CVS-ID: os2/config.h 1.43
CVS-ID: src/ChangeLog 1.2394
CVS-ID: src/Makefile.in 1.86
CVS-ID: src/client.c 1.323
CVS-ID: tools/ChangeLog 1.24
CVS-ID: tools/Makefile.in 1.26
CVS-ID: vms/ChangeLog 1.79
CVS-ID: vms/Makefile.in 1.25
CVS-ID: vms/config.h 1.26
CVS-ID: windows-NT/SCC/ChangeLog 1.43
CVS-ID: windows-NT/SCC/Makefile.in 1.21
CVS-ID: windows-NT/ChangeLog 1.161
CVS-ID: windows-NT/Makefile.in 1.32
CVS-ID: windows-NT/config.h 1.47
CVS-ID: ChangeLog 1.708
CVS-ID: Makefile.in 1.91
CVS-ID: config.h.in 1.74
CVS-ID: configure 1.181
CVS-ID: configure.in 1.183

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -873,6 +873,8 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-krb4             Kerberos 4 directory (default /usr/kerberos)
   --with-gssapi           GSSAPI directory (default autoselects)
+  --with-rsh              The default remote shell CVS will use for :ext:
+                          transport (default rsh)
   --with-editor           The default text editor CVS should use for log
                           messages (default autoselects)
   --with-tmpdir           The temporary directory CVS should use as a default
@@ -9399,6 +9401,90 @@ fi
 
 
 
+# What remote shell transport should our client cvs default to using?
+
+# Check whether --with-rsh or --without-rsh was given.
+if test "${with_rsh+set}" = set; then
+  withval="$with_rsh"
+
+else
+  with_rsh="rsh ssh"
+fi;
+
+if test no = "$with_rsh"; then
+  { echo "$as_me:$LINENO: WARNING: Failed to find usable remote shell. Using 'rsh'." >&5
+echo "$as_me: WARNING: Failed to find usable remote shell. Using 'rsh'." >&2;}
+  with_rsh=rsh
+elif test yes = "$with_rsh"; then
+  # Make --with-rsh mean the same thing as --with-rsh=rsh
+  with_rsh=rsh
+fi
+
+if echo $with_rsh |grep ^/ >/dev/null; then
+  # If $with_rsh is an absolute path, issue a warning if the executable
+  # doesn't exist or isn't usable, but then trust the user and use it
+  # regardless
+  with_default_rsh=$with_rsh
+  echo "$as_me:$LINENO: checking for a remote shell" >&5
+echo $ECHO_N "checking for a remote shell... $ECHO_C" >&6
+  if ! test -f $with_rsh \
+      || ! test -x $with_rsh; then
+    # warn the user that they may encounter problems
+    { echo "$as_me:$LINENO: WARNING: $with_rsh is not a path to an executable file" >&5
+echo "$as_me: WARNING: $with_rsh is not a path to an executable file" >&2;}
+  fi
+else
+  # Search for a remote shell
+  for ac_prog in $with_rsh
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_with_default_rsh+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$with_default_rsh"; then
+  ac_cv_prog_with_default_rsh="$with_default_rsh" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_with_default_rsh="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+with_default_rsh=$ac_cv_prog_with_default_rsh
+if test -n "$with_default_rsh"; then
+  echo "$as_me:$LINENO: result: $with_default_rsh" >&5
+echo "${ECHO_T}$with_default_rsh" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$with_default_rsh" && break
+done
+test -n "$with_default_rsh" || with_default_rsh=""rsh""
+
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define RSH_DFLT "$with_default_rsh"
+_ACEOF
+
+
+
 
 
 
@@ -10661,6 +10747,7 @@ s,@LIBOBJS@,$LIBOBJS,;t t
 s,@HAVE_PUTENV@,$HAVE_PUTENV,;t t
 s,@KRB4@,$KRB4,;t t
 s,@includeopt@,$includeopt,;t t
+s,@with_default_rsh@,$with_default_rsh,;t t
 s,@EDITOR@,$EDITOR,;t t
 CEOF
 
