* configure.in: Add support for <pam/pam_appl.h> to allow --enable-pam to work on MacOSX 10.2 and newer. * configure, config.h.in: Regenerated.
* src/server.c: Add support for <pam/pam_appl.h> to allow
--enable-pam to work on MacOSX 10.2 and newer.

* windows-NT/config.h.in.in: Syncronize with ../config.h.in file.
Added: #undef HAVE_DECL_MEMRCHR, #undef HAVE_PAM_PAM_APPL_H,
#undef HAVE_SECURITY_PAM_APPL_H
* windows-NT/config.h, windows-NT/config.h.in: Regenerated.

CVS-ID: src/ChangeLog 1.3177
CVS-ID: src/server.c 1.428
CVS-ID: windows-NT/ChangeLog 1.297
CVS-ID: windows-NT/config.h 1.134
CVS-ID: windows-NT/config.h.in 1.63
CVS-ID: windows-NT/config.h.in.in 1.29
CVS-ID: ChangeLog 1.1196
CVS-ID: config.h.in 1.165
CVS-ID: configure 1.383
CVS-ID: configure.in 1.350

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -38551,6 +38551,8 @@ else
 fi;
 
 if test yes = $enable_pam; then
+  ac_pam_header_available=
+
   if test "${ac_cv_header_security_pam_appl_h+set}" = set; then
   echo "$as_me:$LINENO: checking for security/pam_appl.h" >&5
 echo $ECHO_N "checking for security/pam_appl.h... $ECHO_C" >&6
@@ -38690,6 +38692,173 @@ echo "${ECHO_T}$ac_cv_header_security_pam_appl_h" >&6
 fi
 if test $ac_cv_header_security_pam_appl_h = yes; then
 
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SECURITY_PAM_APPL_H 1
+_ACEOF
+
+    ac_pam_header_available=1
+fi
+
+
+
+  if test -z "$ac_pam_header_available"; then
+  if test "${ac_cv_header_pam_pam_appl_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for pam/pam_appl.h" >&5
+echo $ECHO_N "checking for pam/pam_appl.h... $ECHO_C" >&6
+if test "${ac_cv_header_pam_pam_appl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_pam_pam_appl_h" >&5
+echo "${ECHO_T}$ac_cv_header_pam_pam_appl_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking pam/pam_appl.h usability" >&5
+echo $ECHO_N "checking pam/pam_appl.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <pam/pam_appl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking pam/pam_appl.h presence" >&5
+echo $ECHO_N "checking pam/pam_appl.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pam/pam_appl.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: pam/pam_appl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: pam/pam_appl.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: pam/pam_appl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: pam/pam_appl.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: pam/pam_appl.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: pam/pam_appl.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: pam/pam_appl.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pam/pam_appl.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: pam/pam_appl.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to bug-cvs@gnu.org ##
+## ------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for pam/pam_appl.h" >&5
+echo $ECHO_N "checking for pam/pam_appl.h... $ECHO_C" >&6
+if test "${ac_cv_header_pam_pam_appl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_pam_pam_appl_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_pam_pam_appl_h" >&5
+echo "${ECHO_T}$ac_cv_header_pam_pam_appl_h" >&6
+
+fi
+if test $ac_cv_header_pam_pam_appl_h = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PAM_PAM_APPL_H 1
+_ACEOF
+
+    ac_pam_header_available=1
+fi
+
+
+  fi
+
+  if test -z "$ac_pam_header_available"; then
+    { { echo "$as_me:$LINENO: error: Could not find PAM headers" >&5
+echo "$as_me: error: Could not find PAM headers" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_PAM 1
 _ACEOF
@@ -38771,14 +38940,7 @@ echo "$as_me: error: Could not find PAM libraries but the headers exist.
 
 fi
 
-else
-  { { echo "$as_me:$LINENO: error: Could not find PAM headers" >&5
-echo "$as_me: error: Could not find PAM headers" >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-
-
+  fi
 fi
 
 
