Merge changes from signed-commits4.
CVS-ID: contrib/pam/Makefile.in 1.47
CVS-ID: contrib/Makefile.in 1.126
CVS-ID: diff/Makefile.in 1.95
CVS-ID: doc/i18n/pt_BR/Makefile.in 1.31
CVS-ID: doc/i18n/Makefile.in 1.30
CVS-ID: doc/ChangeLog 1.954
CVS-ID: doc/Makefile.in 1.142
CVS-ID: doc/RCSFILES 1.17
CVS-ID: doc/cvs.1 1.43
CVS-ID: doc/cvs.texinfo 1.680
CVS-ID: doc/cvsclient.texi 1.144
CVS-ID: doc/stamp-1 1.85
CVS-ID: doc/stamp-vti 1.181
CVS-ID: doc/version-client.texi 1.85
CVS-ID: doc/version.texi 1.182
CVS-ID: lib/ChangeLog 1.504
CVS-ID: lib/Makefile.am 1.109
CVS-ID: lib/Makefile.gnulib 1.71
CVS-ID: lib/Makefile.in 1.207
CVS-ID: lib/base64.c 1.2
CVS-ID: lib/base64.h 1.2
CVS-ID: lib/wait.h 1.6
CVS-ID: m4/ChangeLog 1.164
CVS-ID: m4/base64.m4 1.2
CVS-ID: m4/gnulib-cache.m4 1.7
CVS-ID: m4/gnulib-comp.m4 1.15
CVS-ID: m4/uint32_t.m4 1.6
CVS-ID: maint-aux/Makefile.in 1.28
CVS-ID: man/Makefile.in 1.97
CVS-ID: src/ChangeLog 1.3376
CVS-ID: src/Makefile.am 1.48
CVS-ID: src/Makefile.in 1.168
CVS-ID: src/add.c 1.122
CVS-ID: src/admin.c 1.113
CVS-ID: src/annotate.c 1.22
CVS-ID: src/base.c 1.2
CVS-ID: src/base.h 1.2
CVS-ID: src/buffer.c 1.71
CVS-ID: src/buffer.h 1.28
CVS-ID: src/checkin.c 1.57
CVS-ID: src/checkout.c 1.146
CVS-ID: src/classify.c 1.38
CVS-ID: src/classify.h 1.2
CVS-ID: src/client.c 1.446
CVS-ID: src/client.h 1.62
CVS-ID: src/commit.c 1.259
CVS-ID: src/create_adm.c 1.53
CVS-ID: src/cvs.h 1.347
CVS-ID: src/diff.c 1.117
CVS-ID: src/diff.h 1.2
CVS-ID: src/difflib.c 1.2
CVS-ID: src/difflib.h 1.2
CVS-ID: src/edit.c 1.92
CVS-ID: src/edit.h 1.13
CVS-ID: src/entries.c 1.67
CVS-ID: src/entries.h 1.2
CVS-ID: src/fileattr.c 1.37
CVS-ID: src/filesubr.c 1.107
CVS-ID: src/filesubr.h 1.2
CVS-ID: src/find_names.c 1.44
CVS-ID: src/gpg.c 1.2
CVS-ID: src/gpg.h 1.2
CVS-ID: src/hash.c 1.49
CVS-ID: src/hash.h 1.22
CVS-ID: src/history.c 1.97
CVS-ID: src/ignore.c 1.57
CVS-ID: src/ignore.h 1.2
CVS-ID: src/import.c 1.176
CVS-ID: src/lock.c 1.119
CVS-ID: src/log.c 1.104
CVS-ID: src/logmsg.c 1.101
CVS-ID: src/logmsg.h 1.2
CVS-ID: src/ls.c 1.19
CVS-ID: src/main.c 1.266
CVS-ID: src/mkmodules.c 1.97
CVS-ID: src/modules.c 1.99
CVS-ID: src/no_diff.c 1.39
CVS-ID: src/no_diff.h 1.2
CVS-ID: src/parseinfo.c 1.86
CVS-ID: src/parseinfo.h 1.8
CVS-ID: src/patch.c 1.107
CVS-ID: src/rcs.c 1.362
CVS-ID: src/rcs.h 1.84
CVS-ID: src/rcscmds.c 1.73
CVS-ID: src/recurse.c 1.116
CVS-ID: src/recurse.h 1.2
CVS-ID: src/release.c 1.72
CVS-ID: src/remove.c 1.64
CVS-ID: src/repos.c 1.42
CVS-ID: src/repos.h 1.2
CVS-ID: src/root.c 1.125
CVS-ID: src/root.h 1.24
CVS-ID: src/run.c 1.63
CVS-ID: src/run.h 1.2
CVS-ID: src/sanity.config.sh.in 1.4
CVS-ID: src/sanity.sh 1.1126
CVS-ID: src/server.c 1.459
CVS-ID: src/server.h 1.46
CVS-ID: src/sign.c 1.2
CVS-ID: src/sign.h 1.2
CVS-ID: src/status.c 1.69
CVS-ID: src/subr.c 1.149
CVS-ID: src/subr.h 1.8
CVS-ID: src/tag.c 1.145
CVS-ID: src/update.c 1.261
CVS-ID: src/verify.c 1.2
CVS-ID: src/verify.h 1.2
CVS-ID: src/vers_ts.c 1.66
CVS-ID: src/vers_ts.h 1.2
CVS-ID: src/watch.c 1.46
CVS-ID: src/wrapper.c 1.48
CVS-ID: src/wrapper.h 1.2
CVS-ID: src/zlib.c 1.34
CVS-ID: tools/Makefile.in 1.87
CVS-ID: vms/Makefile.in 1.90
CVS-ID: windows-NT/SCC/Makefile.in 1.81
CVS-ID: windows-NT/Makefile.in 1.119
CVS-ID: windows-NT/config.h 1.179
CVS-ID: windows-NT/config.h.in 1.107
CVS-ID: windows-NT/stamp-chi 1.93
CVS-ID: ChangeLog 1.1292
CVS-ID: GPG-TODO 1.2
CVS-ID: Makefile.in 1.187
CVS-ID: aclocal.m4 1.153
CVS-ID: config.h.in 1.197
CVS-ID: configure 1.443
CVS-ID: configure.in 1.364

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -327,7 +327,7 @@ ac_includes_default="\
 
 gl_header_list=
 gl_func_list=
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar ac_prefix_program MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT RANLIB ac_ct_RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LN_S PERL CSH MKTEMP SENDMAIL PR ROFF PS2PDF TEXI2DVI MAKE_TARGETS_IN_VPATH_TRUE MAKE_TARGETS_IN_VPATH_FALSE LIBOBJS GL_COND_LIBTOOL_TRUE GL_COND_LIBTOOL_FALSE ALLOCA ALLOCA_H SYS_SOCKET_H STDBOOL_H HAVE__BOOL FNMATCH_H YACC YFLAGS LIB_CLOCK_GETTIME GETOPT_H GLOB_H LIB_NANOSLEEP HAVE_LONG_64BIT HAVE_LONG_LONG_64BIT STDINT_H UNISTD_H EOVERFLOW MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE build build_cpu build_vendor build_os host host_cpu host_vendor host_os INTL_MACOSX_LIBS LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB cvs_client_objects KRB4 ZLIB_SUBDIRS ZLIB_CPPFLAGS ZLIB_LIBS with_default_rsh RSH_DFLT EDITOR LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar ac_prefix_program MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT RANLIB ac_ct_RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LN_S PERL CSH MKTEMP SENDMAIL PR GPG DEFAULT_VERIFY_TEMPLATE ROFF PS2PDF TEXI2DVI MAKE_TARGETS_IN_VPATH_TRUE MAKE_TARGETS_IN_VPATH_FALSE LIBOBJS GL_COND_LIBTOOL_TRUE GL_COND_LIBTOOL_FALSE ALLOCA ALLOCA_H SYS_SOCKET_H STDBOOL_H HAVE__BOOL FNMATCH_H YACC YFLAGS LIB_CLOCK_GETTIME GETOPT_H GLOB_H LIB_NANOSLEEP HAVE_LONG_64BIT HAVE_LONG_LONG_64BIT STDINT_H UNISTD_H EOVERFLOW MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE build build_cpu build_vendor build_os host host_cpu host_vendor host_os INTL_MACOSX_LIBS LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB cvs_client_objects KRB4 ZLIB_SUBDIRS ZLIB_CPPFLAGS ZLIB_LIBS with_default_rsh RSH_DFLT EDITOR LTLIBOBJS'
 ac_subst_files='MKTEMP_SH_FUNCTION'
 
 # Initialize some variables set by options.
@@ -5751,6 +5751,81 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 fi
+# For src/gpg.c
+# Extract the first word of "gpg", so it can be a program name with args.
+set dummy gpg; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_GPG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GPG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GPG="$GPG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_GPG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_GPG" && ac_cv_path_GPG="gpg"
+  ;;
+esac
+fi
+GPG=$ac_cv_path_GPG
+
+if test -n "$GPG"; then
+  echo "$as_me:$LINENO: result: $GPG" >&5
+echo "${ECHO_T}$GPG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test x"$GPG" != xgpg; then
+  # The GPG on at least one of my FreeBSD 4.11 test systems fails to run
+  # because libintl is missing.
+  if $GPG --version >/dev/null 2>&1; then :; else
+    # GPG is broken.  Pretend it isn't there.
+    { echo "$as_me:$LINENO: WARNING: GPG is installed as \`$GPG', but is broken.  Ignoring it." >&5
+echo "$as_me: WARNING: GPG is installed as \`$GPG', but is broken.  Ignoring it." >&2;}
+    GPG=gpg
+  fi
+fi
+if test x"$GPG" != xgpg; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENPGP 1
+_ACEOF
+
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define DEFAULT_SIGN_TEMPLATE "$GPG --detach-sign --output - %t %a -- %s"
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define DEFAULT_SIGN_TEXTMODE "--textmode"
+_ACEOF
+
+DEFAULT_VERIFY_TEMPLATE="$GPG --verify %t %a -- %S %s"
+
+
+cat >>confdefs.h <<_ACEOF
+#define DEFAULT_VERIFY_TEMPLATE "$DEFAULT_VERIFY_TEMPLATE"
+_ACEOF
+
 
 missing_dir=`cd $ac_aux_dir && pwd`
 glocs="$PATH:/usr/local/bin:/usr/contrib/bin:/usr/gnu/bin:/local/bin:/local/gnu/bin:/gnu/bin"
@@ -8757,6 +8832,77 @@ _ACEOF
 
   fi
 
+echo "$as_me:$LINENO: checking for inline" >&5
+echo $ECHO_N "checking for inline... $ECHO_C" >&6
+if test "${ac_cv_c_inline+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_c_inline=no
+for ac_kw in inline __inline__ __inline; do
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#ifndef __cplusplus
+typedef int foo_t;
+static $ac_kw foo_t static_foo () {return 0; }
+$ac_kw foo_t foo () {return 0; }
+#endif
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_inline=$ac_kw; break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+done
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_inline" >&5
+echo "${ECHO_T}$ac_cv_c_inline" >&6
+
+
+case $ac_cv_c_inline in
+  inline | yes) ;;
+  *)
+    case $ac_cv_c_inline in
+      no) ac_val=;;
+      *) ac_val=$ac_cv_c_inline;;
+    esac
+    cat >>confdefs.h <<_ACEOF
+#ifndef __cplusplus
+#define inline $ac_val
+#endif
+_ACEOF
+    ;;
+esac
+
 echo "$as_me:$LINENO: checking for C/C++ restrict keyword" >&5
 echo $ECHO_N "checking for C/C++ restrict keyword... $ECHO_C" >&6
 if test "${gl_cv_c_restrict+set}" = set; then
@@ -9274,77 +9420,6 @@ done
     SYS_SOCKET_H='sys/socket.h'
   fi
 
-
-echo "$as_me:$LINENO: checking for inline" >&5
-echo $ECHO_N "checking for inline... $ECHO_C" >&6
-if test "${ac_cv_c_inline+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_c_inline=no
-for ac_kw in inline __inline__ __inline; do
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#ifndef __cplusplus
-typedef int foo_t;
-static $ac_kw foo_t static_foo () {return 0; }
-$ac_kw foo_t foo () {return 0; }
-#endif
-
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_c_inline=$ac_kw; break
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-done
-
-fi
-echo "$as_me:$LINENO: result: $ac_cv_c_inline" >&5
-echo "${ECHO_T}$ac_cv_c_inline" >&6
-
-
-case $ac_cv_c_inline in
-  inline | yes) ;;
-  *)
-    case $ac_cv_c_inline in
-      no) ac_val=;;
-      *) ac_val=$ac_cv_c_inline;;
-    esac
-    cat >>confdefs.h <<_ACEOF
-#ifndef __cplusplus
-#define inline $ac_val
-#endif
-_ACEOF
-    ;;
-esac
 
 
 
@@ -17451,6 +17526,12 @@ done
   :
 
   fi
+
+
+
+
+
+
 
 
 
@@ -45721,6 +45802,8 @@ s,@CSH@,$CSH,;t t
 s,@MKTEMP@,$MKTEMP,;t t
 s,@SENDMAIL@,$SENDMAIL,;t t
 s,@PR@,$PR,;t t
+s,@GPG@,$GPG,;t t
+s,@DEFAULT_VERIFY_TEMPLATE@,$DEFAULT_VERIFY_TEMPLATE,;t t
 s,@ROFF@,$ROFF,;t t
 s,@PS2PDF@,$PS2PDF,;t t
 s,@TEXI2DVI@,$TEXI2DVI,;t t
