Regenerated.
CVS-ID: contrib/pam/Makefile.in 1.41
CVS-ID: contrib/Makefile.in 1.120
CVS-ID: diff/Makefile.in 1.89
CVS-ID: doc/i18n/pt_BR/Makefile.in 1.25
CVS-ID: doc/i18n/Makefile.in 1.24
CVS-ID: doc/Makefile.in 1.136
CVS-ID: doc/stamp-1 1.75
CVS-ID: doc/stamp-vti 1.170
CVS-ID: doc/version-client.texi 1.75
CVS-ID: doc/version.texi 1.171
CVS-ID: lib/Makefile.in 1.200
CVS-ID: maint-aux/Makefile.in 1.19
CVS-ID: man/Makefile.in 1.91
CVS-ID: src/Makefile.in 1.162
CVS-ID: tools/Makefile.in 1.81
CVS-ID: vms/Makefile.in 1.84
CVS-ID: windows-NT/SCC/Makefile.in 1.75
CVS-ID: windows-NT/Makefile.in 1.113
CVS-ID: windows-NT/config.h 1.173
CVS-ID: windows-NT/config.h.in 1.101
CVS-ID: windows-NT/stamp-chi 1.87
CVS-ID: Makefile.in 1.181
CVS-ID: aclocal.m4 1.147
CVS-ID: config.h.in 1.191
CVS-ID: configure 1.430

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1497,8 +1497,6 @@ gl_func_list="$gl_func_list isblank"
 gl_func_list="$gl_func_list mbrtowc"
 gl_func_list="$gl_func_list wcrtomb"
 gl_func_list="$gl_func_list wcscoll"
-gl_header_list="$gl_header_list sys/types.h"
-gl_header_list="$gl_header_list sys/socket.h"
 gl_func_list="$gl_func_list mblen"
 gl_func_list="$gl_func_list mbrlen"
 gl_func_list="$gl_func_list tzset"
@@ -14615,18 +14613,6 @@ _ACEOF
 
 
 
-
-
-
-
-
-
-
-
-
-
-
-
   echo "$as_me:$LINENO: checking for inttypes.h" >&5
 echo $ECHO_N "checking for inttypes.h... $ECHO_C" >&6
 if test "${gt_cv_header_inttypes_h+set}" = set; then
@@ -24177,10 +24163,76 @@ fi
 
 
 
+  echo "$as_me:$LINENO: checking whether off_t can be used in a switch statement" >&5
+echo $ECHO_N "checking whether off_t can be used in a switch statement... $ECHO_C" >&6
+if test "${gl_cv_type_off_t_switch+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+off_t o = -1;
+	   switch (o)
+	     {
+	     case -2:
+	       return 1;
+	     case -1:
+	       return 2;
+	     default:
+	       return 0;
+	     }
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gl_cv_type_off_t_switch=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gl_cv_type_off_t_switch=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $gl_cv_type_off_t_switch" >&5
+echo "${ECHO_T}$gl_cv_type_off_t_switch" >&6
+  if test $gl_cv_type_off_t_switch = yes; then
+
 cat >>confdefs.h <<\_ACEOF
 #define _REGEX_LARGE_OFFSETS 1
 _ACEOF
 
+  fi
 
 
 
@@ -26679,92 +26731,7 @@ _ACEOF
 
   fi
 
-
-
-  :
-
-
-
-
-
-
-
-
-  echo "$as_me:$LINENO: checking for socklen_t" >&5
-echo $ECHO_N "checking for socklen_t... $ECHO_C" >&6
-if test "${ac_cv_type_socklen_t+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-#ifdef HAVE_SYS_TYPES_H
-# include <sys/types.h>
-#endif
-#ifdef HAVE_SYS_SOCKET_H
-# include <sys/socket.h>
-#endif)
-
-
-int
-main ()
-{
-if ((socklen_t *) 0)
-  return 0;
-if (sizeof (socklen_t))
-  return 0;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_type_socklen_t=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_type_socklen_t=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $ac_cv_type_socklen_t" >&5
-echo "${ECHO_T}$ac_cv_type_socklen_t" >&6
-if test $ac_cv_type_socklen_t = yes; then
-  :
-else
-
-cat >>confdefs.h <<\_ACEOF
-#define socklen_t int
-_ACEOF
-
-fi
-
-
+  gl_SOCKLEN_T
 
   echo "$as_me:$LINENO: checking for ssize_t" >&5
 echo $ECHO_N "checking for ssize_t... $ECHO_C" >&6
