Regenerated.
CVS-ID: contrib/pam/Makefile.in 1.28
CVS-ID: contrib/Makefile.in 1.105
CVS-ID: diff/Makefile.in 1.76
CVS-ID: doc/i18n/pt_BR/Makefile.in 1.12
CVS-ID: doc/i18n/Makefile.in 1.11
CVS-ID: maint-aux/Makefile.in 1.6
CVS-ID: maint-aux/gnulib-filelist.txt 1.5
CVS-ID: man/Makefile.in 1.78
CVS-ID: src/Makefile.in 1.148
CVS-ID: tools/Makefile.in 1.68
CVS-ID: vms/Makefile.in 1.70
CVS-ID: windows-NT/SCC/Makefile.in 1.62
CVS-ID: windows-NT/Makefile.in 1.95
CVS-ID: windows-NT/config.h 1.142
CVS-ID: windows-NT/config.h.in 1.71
CVS-ID: windows-NT/stamp-chi 1.58
CVS-ID: windows-NT/stdbool.h 1.3
CVS-ID: windows-NT/stdint.h 1.3
CVS-ID: Makefile.in 1.167
CVS-ID: aclocal.m4 1.136
CVS-ID: config.h.in 1.172
CVS-ID: configure 1.395

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11607,6 +11607,142 @@ esac
 
 
 
+  echo "$as_me:$LINENO: checking whether <limits.h> defines MIN and MAX" >&5
+echo $ECHO_N "checking whether <limits.h> defines MIN and MAX... $ECHO_C" >&6
+if test "${gl_cv_minmax_in_limits_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <limits.h>
+int x = MIN (42, 17);
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gl_cv_minmax_in_limits_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gl_cv_minmax_in_limits_h=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $gl_cv_minmax_in_limits_h" >&5
+echo "${ECHO_T}$gl_cv_minmax_in_limits_h" >&6
+  if test $gl_cv_minmax_in_limits_h = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MINMAX_IN_LIMITS_H 1
+_ACEOF
+
+  fi
+
+
+
+
+
+
+  echo "$as_me:$LINENO: checking whether <sys/param.h> defines MIN and MAX" >&5
+echo $ECHO_N "checking whether <sys/param.h> defines MIN and MAX... $ECHO_C" >&6
+if test "${gl_cv_minmax_in_sys_param_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/param.h>
+int x = MIN (42, 17);
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gl_cv_minmax_in_sys_param_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gl_cv_minmax_in_sys_param_h=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $gl_cv_minmax_in_sys_param_h" >&5
+echo "${ECHO_T}$gl_cv_minmax_in_sys_param_h" >&6
+  if test $gl_cv_minmax_in_sys_param_h = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MINMAX_IN_SYS_PARAM_H 1
+_ACEOF
+
+  fi
+
+
+
+
+
+
+
+
 
 
 
@@ -20094,11 +20230,6 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-cat >>confdefs.h <<\_ACEOF
-#define GETTIMEOFDAY_CLOBBERS_LOCALTIME_BUFFER 1
-_ACEOF
-
-
 
 
   fi
@@ -20724,6 +20855,9 @@ done
   if test $ac_cv_func_memrchr = no; then
     :
   fi
+
+
+
 
     echo "$as_me:$LINENO: checking whether mkdir fails due to a trailing slash" >&5
 echo $ECHO_N "checking whether mkdir fails due to a trailing slash... $ECHO_C" >&6
