* configure.in: Set package configuration string here (e.g. "client/server").
CVS-ID: ChangeLog 1.1355
CVS-ID: Makefile.in 1.204
CVS-ID: config.h.in 1.225
CVS-ID: configure 1.482
CVS-ID: configure.in 1.380

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -821,6 +821,7 @@ ZLIB_LIBS
 with_default_rsh
 RSH_DFLT
 EDITOR
+PACKAGE_CONFIG
 LTLIBOBJS'
 ac_subst_files='MKTEMP_SH_FUNCTION'
       ac_precious_vars='build_alias
@@ -46998,6 +46999,34 @@ fi
 
 
 
+if test x"$enable_client" != xno; then
+	if test x"$enable_server" != xno; then
+		# yes,yes
+		PACKAGE_APPEND=" (client/server)"
+	else
+		# yes,no
+		PACKAGE_APPEND=" (client)"
+	fi
+else
+	if test x"$enable_server" != xno; then
+		# no,yes
+		PACKAGE_APPEND=" (server)"
+	else
+		# no,no
+		# no change
+		PACKAGE_APPEND=
+	fi
+fi
+PACKAGE_CONFIG="Concurrent Versions System (CVS) 1.12.13.1$PACKAGE_APPEND"
+
+
+cat >>confdefs.h <<_ACEOF
+#define PACKAGE_CONFIG "$PACKAGE_CONFIG"
+_ACEOF
+
+
+
+
 
 { echo "$as_me:$LINENO: checking for cygwin32" >&5
 echo $ECHO_N "checking for cygwin32... $ECHO_C" >&6; }
@@ -48045,7 +48074,7 @@ ZLIB_LIBS!$ZLIB_LIBS$ac_delim
 with_default_rsh!$with_default_rsh$ac_delim
 RSH_DFLT!$RSH_DFLT$ac_delim
 EDITOR!$EDITOR$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
+PACKAGE_CONFIG!$PACKAGE_CONFIG$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -48080,6 +48109,50 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 1; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-3.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -48333,7 +48406,7 @@ s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 s&@MKDIR_P@&$ac_MKDIR_P&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
