* configure.in: Add support for --with-ssh and CVS_SSH. * NEWS: Note that :extssh: looks to CVS_SSH rather tha CVS_RSH. * Makefile.in, config.h.in, configure: Regenerated.
* doc/cvs.texinfo: Document use of --with-ssh flag to configure and
how :extssh: uses the CVS_SSH environment variable or "ssh".
* doc/stamp-vti, doc/version.texi: Regenerated.

* src/filesubr.c (xreadlink): s/128/BUFSIZ/ avoid magic numbers.

* src/client.c (start_rsh_server): Use CVS_SSH for the :extssh:
method or fall back to "ssh" as set using the --with-ssh flag to
configure.

* windows-NT/config.h.in (RSH_DFLT, SSH_DFLT): Add default values.
* windows-NT/Makefile.in, config.h: Regenerated.

CVS-ID: windows-NT/config.h 1.46.2.40
CVS-ID: configure 1.174.2.82
CVS-ID: configure.in 1.176.2.73

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -716,6 +716,7 @@ LIBOBJS
 KRB4
 includeopt
 EDITOR
+with_default_ssh
 with_default_rsh
 LTLIBOBJS'
 ac_subst_files='MKTEMP_SH_FUNCTION'
@@ -1365,6 +1366,8 @@ Optional Packages:
   --with-gssapi           GSSAPI directory (default autoselects)
   --with-editor           The default text editor CVS should use for log
                           messages (default autoselects)
+  --with-ssh              The default remote shell CVS will use for :extssh:
+                          transport (default autodetects)
   --with-rsh              The default remote shell CVS will use for :ext:
                           transport (default autodetects)
   --with-tmpdir           The temporary directory CVS should use as a default
@@ -12125,13 +12128,100 @@ _ACEOF
 
 
 
+# What remote shell transport should the :extssh: client cvs default to using?
+
+# Check whether --with-ssh was given.
+if test "${with_ssh+set}" = set; then
+  withval=$with_ssh;
+else
+  with_ssh="ssh lsh ssh2"
+fi
+
+
+if test no = "$with_ssh"; then
+  { echo "$as_me:$LINENO: WARNING: Failed to find usable remote shell. Using 'ssh'." >&5
+echo "$as_me: WARNING: Failed to find usable remote shell. Using 'ssh'." >&2;}
+  with_ssh=ssh
+elif test yes = "$with_ssh"; then
+  # Make --with-ssh mean the same thing as --with-ssh=ssh
+  with_ssh=ssh
+fi
+
+if echo $with_ssh |grep ^/ >/dev/null; then
+  # If $with_ssh is an absolute path, issue a warning if the executable
+  # doesn't exist or isn't usable, but then trust the user and use it
+  # regardless
+  with_default_ssh=$with_ssh
+  { echo "$as_me:$LINENO: checking for a remote shell" >&5
+echo $ECHO_N "checking for a remote shell... $ECHO_C" >&6; }
+  if ! test -f $with_ssh \
+      || ! test -x $with_ssh; then
+    # warn the user that they may encounter problems
+    { echo "$as_me:$LINENO: WARNING: $with_ssh is not a path to an executable file" >&5
+echo "$as_me: WARNING: $with_ssh is not a path to an executable file" >&2;}
+  fi
+else
+  # Search for a remote shell
+  for ac_prog in $with_ssh
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_with_default_ssh+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$with_default_ssh"; then
+  ac_cv_prog_with_default_ssh="$with_default_ssh" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_with_default_ssh="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+with_default_ssh=$ac_cv_prog_with_default_ssh
+if test -n "$with_default_ssh"; then
+  { echo "$as_me:$LINENO: result: $with_default_ssh" >&5
+echo "${ECHO_T}$with_default_ssh" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$with_default_ssh" && break
+done
+test -n "$with_default_ssh" || with_default_ssh=""ssh""
+
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define SSH_DFLT "$with_default_ssh"
+_ACEOF
+
+
+
+
 # What remote shell transport should our client cvs default to using?
 
 # Check whether --with-rsh was given.
 if test "${with_rsh+set}" = set; then
   withval=$with_rsh;
 else
-          with_rsh="remsh rsh ssh"
+          with_rsh="remsh rsh ssh lsh ssh2"
 fi
 
 
@@ -14034,11 +14124,12 @@ LIBOBJS!$LIBOBJS$ac_delim
 KRB4!$KRB4$ac_delim
 includeopt!$includeopt$ac_delim
 EDITOR!$EDITOR$ac_delim
+with_default_ssh!$with_default_ssh$ac_delim
 with_default_rsh!$with_default_rsh$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 9; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
